### ISSUE TITLE
AttributeError: 'PSourcer' object has no attribute 'set_output'

### ISSUE THREAD

**Issue by theChaosCoder** [rlaphoenix/pvsfunc#2]
Maybe I'm just using it wrong, but I assume it should be used like any source filter?

With `clip = PSourcer(r"f:\ep1_1.vob", debug=False)` I get this error ` AttributeError: 'PSourcer' object has no attribute 'set_output'`

The d2v is correctly generated. All modules installed via pip.

Windows 10 x64
VS R52
pvsfunc 3.15.4

```
import vapoursynth as vs
core = vs.core
from pvsfunc import PSourcer

clip = PSourcer(r"f:\ep1_1.vob", debug=False)
clip.set_output()
```

**Comment by rlaphoenix** [comment]
The output from PSourcer class is not a clip, but you can access its clip via `PSourcer( ... ).clip` and then `set_output()` on it

**Comment by theChaosCoder** [comment]
Ahh yes, works now. Let's see if I get PDeinterlacer to work ^^"

**Comment by theChaosCoder** [comment]
Ok it seems it has to be a python function. Native plugins can not be passed directly.
I think it would be nice if the doc could show a simple script example to the user for an easier start :-)

```
def ivtc(clip):
	return clip.vivtc.VFM(0)

clip = PDeinterlacer(clip, kernel=ivtc).clip
```

**Comment by rlaphoenix** [comment]
You can use plugins as a PDeinterlacer kernel, it just needs to have a tff argument in the function (case insensitive). In a case like clip.vivtc.VFM, which uses `order` as an int, and not `tff` as a bool, you can do a `kernel=lambda c, tff: clip.vivtc.VFM(c, 1 if tff else 0)`. Ideally, pvsfunc would support providing the tff/order as an int and bool and support both `order` and `tff` argument names.

There is an example use of pvsfunc in the [VSMPEG](https://github.com/rlaphoenix/vsmpeg) project, which you can check out.
